### ISSUE TITLE
Does shared_map support custom data types?

### ISSUE THREAD

**Issue by cddqssc** [gmpassos/shared_map#2]
Thank you for providing this package， I have a question: does shared_map support custom data types?
Something like:
 var store1 = SharedStore('t1');
 var m1 = await store1.getSharedMap<String, **_CustomType_**>('m1');

**Comment by gmpassos** [comment]
You can use any type supported by Isolate SendPort:

https://api.dartlang.org/stable/dart-isolate/SendPort/send.html

Best regards

**Comment by cddqssc** [comment]
> You can use any type supported by Isolate SendPort:
> 
> https://api.dartlang.org/stable/dart-isolate/SendPort/send.html
> 
> Best regards

I have tested it, and it works well. 

Another question, based on the example you provided, it seems that we don't need to manually release memory because the get and put operations are working on the same memory block (for the same key). 

So, each put operation doesn't allocate new memory(for the same key), so there won't be memory leaks. 

Is my understanding correct?

**Comment by gmpassos** [comment]
Dart memory is handled by the GC. If nothing is pointing to the object the GC will collect it. 

The only place that holds data is the SharedMap in the initial Isolate, since the other Isolates only have a "client" version of the SharedMap.
